### ISSUE TITLE
Nominating @jamesknelson as a member of @mdx-js

### ISSUE THREAD

**Issue by johno** [unifiedjs/governance#10]
I'd like to nominate @jamesknelson as a member of @mdx-js merger team.

He built MDXC which was an inspirational library when building MDX and is an active community member building [tooling](https://github.com/frontarm/mdx-util) that improves the ecosystem.

His thoughts and experience will also be important when we build out interleaving in the library since we will likely closely model it off of the API he designed and implemented in MDXC.

**Comment by wooorm** [comment]
Landed! Welcome @jamesknelson 👋
