### ISSUE TITLE
Project onboarding process

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/governance#11]
Where does onboarding new projects being contributed from the community fit into the governance?

For example @aecepoglu is generously offering to contribute https://github.com/aecepoglu/retext-language-server to the retext organization.

Would that be considered an "initiative" that would be decided by the [retext team](https://github.com/unifiedjs/governance#retext-team)?

**Comment by wooorm** [comment]
This is described by the [Project Governance Grant Policy](https://github.com/unifiedjs/governance/blob/master/governance-grant.md). However, that policy is more of a “donation” policy, for inactive projects or inactive maintainers, which is reflected in loss of release rights for the outside maintainer/collaborator (in this case, @aecepoglu).

Alternatively, outside maintainers can become members (same rights/responsibilities but for all related projects, in this case, everything under @retextjs) or even members on the releasers team (same as before but with publish rights for all projects under the org). However, this seems a bit much in this case.

Also, from the grant:

> Organization teams maintain projects in the ecosystem around their area of expertise from inside an organization. Projects in the ecosystem can also be maintained outside of an organization: anyone can develop, maintain, and self-govern such projects.

> Outside projects can flourish [...]

---

And back to your question, yes, this is something that’s in the scope of the @retextjs team!

**Comment by wooorm** [comment]
Was this issue more of a question, and can this be closed, or how do you want to proceed here?

**Comment by ChristianMurphy** [comment]
Not sure yet, what is the best channel to reach out to the retext core team?

**Comment by wooorm** [comment]
In the future it would be `retextjs/governance`, but I’m still testing stuff out for `remarkjs/governance` first, and building the tooling for that.

Maybe an issue on retextjs/retext, CCing all the members?

**Comment by ChristianMurphy** [comment]
Sounds good, thanks @wooorm!
