### ISSUE TITLE
Nominating @Jarred-Sumner as a member of @mdx-js

### ISSUE THREAD

**Issue by johno** [unifiedjs/governance#15]
I'd like to nominate @Jarred-Sumner as a member of the @mdx-js merger team.

He's been has been submitting solid PR/issue contributions and is building a product on top of MDX core that is certainly familiarizing him with how the core internals work.

**Comment by wooorm** [comment]
Welcome @Jarred-Sumner! You should have received an invite with the correct rights!

**Comment by wooorm** [comment]
Although the docs here are incomplete, please read the core governance document (in the readme here), peruse the other policies, and our code of conduct!
