### ISSUE TITLE
Nominating @BarryThePenguin as a member of @remarkjs, @syntax-tree

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/governance#16]
I'd like to nominate @BarryThePenguin (Jonathan Haines) as a member of the @remarkjs and @syntax-tree merger teams.

He's been helping out and using both organisations for years now!

**Comment by BarryThePenguin** [comment]
Thanks @wooorm 👋🏻

**Comment by wooorm** [comment]
Welcome @BarryThePenguin! You should have received an invite with the correct rights!

Although the docs here are incomplete, please read the core governance document (in the readme here), peruse the other policies, and our code of conduct!
