### ISSUE TITLE
Nominating @kmck as a member of @remarkjs, @rehypejs, @syntax-tree

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/governance#21]
I'd like to nominate @kmck (Keith McKnight) as a member of the @remarkjs, @rehypejs, and @syntax-tree merger teams.

Keith created [`hast-util-to-dom`](https://github.com/syntax-tree/hast-util-to-dom) and [`hast-util-from-dom`](https://github.com/syntax-tree/hast-util-from-dom), which come together in [`rehype-dom`](https://github.com/rehypejs/rehype-dom): rehype, but using browser APIs, so much smaller! Those have since been moved under syntax-tree and rehype respectively.

I think those are really interest projects, and it’s a sign of a good understanding of the ecosystem, so I think Keith is a great addition to triage, review, and help out!

**Comment by wooorm** [comment]
Welcome @kmck! You should have received an invite with the correct rights!

Although the docs here are incomplete, please read the core governance document (in the readme here), peruse the other policies, and our code of conduct!

We should do a hangout/skype/call in a week or so, to check in with how it’s going and whether there are questions. Could you send me an email with what timezone you’re on and what could work for you?

**Comment by kmck** [comment]
thanks! glad to be here! i'll take a look at the docs and you an email shortly.
