### ISSUE TITLE
Inactive team member review (July)

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/governance#23]
Hi unified collective members! 👋

As described in our [governance document](https://github.com/unifiedjs/governance#core-team), one task of @unifiedjs/core is to review inactive team members, and offboard them. As this is the first time, I’m CCing every non-emeritus member.
After reviewing current members, the following members seem to be inactive and/or have not shown interest in staying on (note that I may have overlooked something):

*   @jamesknelson (@mdx-js)
*   @komaeda (@vfile)
*   @RichardLitt (@retextjs, @unifiedjs/core)
*   @sobolevn (@remarkjs)
*   @timneutkens (@mdx-js)
*   @vhf (@unifiedjs, @rehypejs, @micromark)
*   @zcei (@unifiedjs, @mdx-js, @micromark, @unifiedjs/core)
*   @zeusdeux (@unifiedjs, @mdx-js, @micromark)

Moving to emeritus status does not mean you or your (past) work is not appreciated. Everyone is still welcome in the unified collective and can still contribute or read along. Emeriti can also be reinstated as active members. This isn’t fun, but there there are advantages of an active group of maintainers (such as security).

Typically we take 72 hours before acting upon something like this, but as this is the first time I’d like to use a full week (168 hours) for members to object.
If objecting, please respond with a description why.
Without an objection, I’ll proceed with the offboarding.

Note that anyone at any time may request to be moved to emeritus status, so if you’d also like to change state, reply below. It’s of course understandable that other things are more pressing than unified.

Note: I don’t think it makes sense that @unifiedjs/moderators needs to be “active” (in the form of comments or issues), so I don’t feel @unifiedjs/core should review whether they are active.

/CC @ChristianMurphy @johno @Murderlon @RichardLitt @zcei @zeusdeux @vhf @BarryThePenguin @Rokt33r @kmck @fazouane-marouane @sobolevn @zeke @ChristopherBiscardi @jamesknelson @Jarred-Sumner @silvenon @timneutkens @komaeda

**Comment by ChristianMurphy** [comment]
@wooorm some points of clarification on this.

1. What services used by the collective does this impact? (GitHub, OpenCollective, NPM, etc)
2. What is the metric for determining inactivity?

**Comment by timneutkens** [comment]
I'm still actively monitoring mdx-js/mdx and collaborating with @johno, in most cases John is fast to merge PRs though 😄

**Comment by komaeda** [comment]
👍

**Comment by sobolevn** [comment]
Sorry, but I don't have any extra time to work on `remark` 🙁

**Comment by wooorm** [comment]
> @wooorm some points of clarification on this.
> 1. What services used by the collective does this impact? (GitHub, OpenCollective, NPM, etc)
> 2. What is the metric for determining inactivity?
>
> — [@ChristianMurphy](https://github.com/unifiedjs/governance/issues/23#issuecomment-507390120)

This affects all teams. From those teams, GitHub membership is generated (WIP, hopefully OSS this month). npm is not automated but I hope that happens this month as well. OC membership is currently active membership (except for you and Merlijn, sorry, you both have an invite in your mailbox)

There is no metric. I read all notifications across the orgs and I subjectively “remembered” who has been active recently. I felt like it makes sense to keep this ambiguous, and human, until the dust settles and it’s been done a couple of times.

**Comment by RichardLitt** [comment]
I've read a lot of notifications, but haven't interfaced actively. Happy to be emeritus, but I'm also happy to be on call for anything needed on the moderation team, which I think is more than emeritus work.

**Comment by zeke** [comment]
> npm is not automated but I hope that happens this month as well.

✨ 👀 ✨

**Comment by wooorm** [comment]
> I've read a lot of notifications, but haven't interfaced actively. Happy to be emeritus, but I'm also happy to be on call for anything needed on the moderation team, which I think is more than emeritus work.
>
> — [@RichardLitt](https://github.com/unifiedjs/governance/issues/23#issuecomment-507419723)

I appreciate the work: that’s a lot of notifications! :wink: I think emeritus status can be handle on a per-team basis, so I propose emeritus on retextjs and unifiedjs/core, but staying on as an active moderation team member. Of course, if you’d like, you can stay active on all teams!

**Comment by wooorm** [comment]
To conclude this thread, I have made the following changes to emeritus based on the proposals and the resulting conversations:

* @jamesknelson (@mdx-js)
* @komaeda (@vfile)
* @RichardLitt (@retextjs, @unifiedjs/core)
* @sobolevn (@remarkjs)
* @vhf (@unifiedjs, @rehypejs, @micromark)
* @zcei (@unifiedjs, @mdx-js, @micromark, @unifiedjs/core)
* @zeusdeux (@unifiedjs, @mdx-js, @micromark)

This does not affect these people in other teams.

Thanks folks!
