### ISSUE TITLE
Nominating @sidharthachatterjee as a member of @mdx-js

### ISSUE THREAD

**Issue by johno** [unifiedjs/governance#26]
Sid is a member of Gatsby's core team and has a lot of experience with MDX and remark's Gatsby integrations.

**Comment by wooorm** [comment]
As a merger I assume?

**Comment by johno** [comment]
Correct, yep 👍

**Comment by wooorm** [comment]
Welcome @sidharthachatterjee! You should have received an invite to the GH and npm MDX orgs with the correct rights!

Although the docs are incomplete, please read the core governance document (in the readme here), peruse the other policies, and our code of conduct!

If you’d like to show your membership of the GitHub org to people, you have to publicize your membership: https://help.github.com/en/articles/publicizing-or-hiding-organization-membership.

If you have any questions, you can ask them here, or ask John!

**Comment by sidharthachatterjee** [comment]
Thank you so much @johno and @wooorm! ❤️
