### ISSUE TITLE
Policies

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/governance#6]
Other than governance (#2), we should draft policies on several things.
In general, I think most policies should be followed by organisations, but I think organizations should be allowed to draft their own policies.

* [x] GitHub organization policy (GH-5) — Define how the GitHub orgs, teams, humans, and repos are managed
* [x] project governance grant policy (GH-7) — define how projects by individuals can move under an organisation
* [x] npm organization policy — Define how the npm orgs, teams, humans, and repos are managed. Maybe one org with teams for respectively the collective and the organization teams? Or orgs for each org team?
* [x] on and offboarding policy — define how individuals become members, and members become emeriti
* [x] `.github` policy — define how to add contributing, support, issue and pr templates, can be set-up
* [x] moderation policy — define how violations are handled
* [ ] fund policy — Define who can request an expense on open collective, for what, and who approves them (I think this policy should be followed by the whole collective)
* [x] consensus seeking policy — define how initiatives are approved or rejects, and which changes require such a process
...anything else I’m missing?

**Comment by wooorm** [comment]
Oh, consensus seeking of course! /cc @komaeda 😉

**Comment by RichardLitt** [comment]
The onboarding document. How do I get involved with Unified? How do I join a committee? :)

**Comment by RichardLitt** [comment]
Code of Conduct policy? 

Do you want help drafting these? I'm happy to take on the next one.

**Comment by wooorm** [comment]
Good one, added. And yes, definitely, please!

**Comment by wooorm** [comment]
Another one: `.github` policy

Which just became easier as organisations can now have a [`.github` **repository**](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/).

**Comment by RichardLitt** [comment]
What would the policy contain? Just a list of what documents should be in the .github repository?

**Comment by wooorm** [comment]
Yeah, I’m thinking something like! What to add, when to use `.github` as a repo or when as a directory, how to style them, available support channels, etc?

**Comment by RichardLitt** [comment]
Let's start with https://github.com/unifiedjs/.github/pull/1

**Comment by wooorm** [comment]
I’m closing this because most of these are done, except for the funding policy, which I’ve opened separately as GH-34.

Thanks everyone for voicing your ideas!
