### ISSUE TITLE
Nominating @fazouane-marouane as a member of @micromark, @remarkjs

### ISSUE THREAD

**Issue by wooorm** [unifiedjs/governance#9]
I'd like to nominate @fazouane-marouane for both the @remarkjs and @micromark teams.

Marouane is doing great work with https://github.com/micromark/micromark/pull/4, helped review GH-2, and and previously worked on [remark-jsx](https://github.com/remarkjs/remark-jsx). I think Marouane is a great addition.

cc: @unifiedjs/core

**Comment by wooorm** [comment]
Added, welcome @fazouane-marouane!

**Comment by fazouane-marouane** [comment]
Thanks everybody! Glad to be here 😊
